version: "3"

services:
  naming_server:
    build: naming_server
    image: dfs-naming-server
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_DEBUG: $DJANGO_DEBUG
    volumes:
      - database:/application/database

volumes:
  database:
